# Generated by Django 2.2.3 on 2019-07-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('name', models.CharField(help_text='enter your name', max_length=10)),
                ('gov_id', models.CharField(help_text='enter your govenment ID', max_length=18, primary_key=True, serialize=False)),
                ('contact', models.IntegerField(help_text='enter your phone number')),
                ('date', models.DateField()),
            ],
        ),
    ]
