# Generated by Django 2.2.3 on 2019-08-07 06:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date',
            field=models.DateField(choices=[(datetime.date(2019, 9, 1), '2019-09-01'), (datetime.date(2019, 9, 2), '2019-09-02')]),
        ),
    ]
