# Generated by Django 2.1 on 2019-08-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190807_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='contact',
            field=models.IntegerField(help_text='请输入您的联系方式'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gov_id',
            field=models.CharField(help_text='请输入您的身份证号', max_length=18, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='name',
            field=models.CharField(help_text='请输入您的姓名', max_length=10),
        ),
    ]
